name = "FastGeoProjections"
uuid = "981663e8-0c94-46dd-b2cf-efc8480900ec"
authors = ["alex s. gardner <alex.s.gardner@jpl.nasa.gov>"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
